name: calamari
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - tensorflow>=2.0
  - lxml
  - scikit-image>=0.15.0
  - tqdm
  - python-bidi
  - edit_distance
  - xlsxwriter
  - pip:
    - git+https://github.com/Calamari-OCR/calamari.git@master
